## Importing the Python Libraries

In [1]:
%matplotlib inline
import numpy as np
import math
import pandas as pd
from IPython.display import Image
from IPython.display import HTML
from IPython.display import Markdown, display
def printmd(string):display(Markdown(string))
import seaborn as sns
import statsmodels.api as sm
from scipy.stats import boxcox
pd.options.display.max_rows = 100
import matplotlib.pyplot as plt
from scipy.stats import norm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import quantile_transform
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import OneHotEncoder  ##. better to use dummy from pandas 
from sklearn.preprocessing import PowerTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae


from sklearn.decomposition import PCA

## Reading the dataframe

In [2]:
def load_original_data():
    filename = "Data/demographic country data.xlsx"
    file1 = pd.read_excel (filename, index_col=False)
    #hk_df = pd.read_csv(filename, index_col=False)
    return file1

In [3]:
df1 = load_original_data()
df1

,Row Labels,% of females ages 15-49 having comprehensive correct knowledge about HIV (2 prevent ways and reject 3 misconceptions),% of males ages 15-49 having comprehensive correct knowledge about HIV (2 prevent ways and reject 3 misconceptions),"Adolescent fertility rate (births per 1,000 women ages 15-19)",Adults (ages 15+) and children (0-14 years) living with HIV,Adults (ages 15+) and children (ages 0-14) newly infected with HIV,Adults (ages 15+) living with HIV,Adults (ages 15+) newly infected with HIV,"Age at first marriage, female","Age at first marriage, male",...,Urban population (% of total),Urban population growth (annual %),Urban poverty headcount ratio at national poverty lines (% of urban population),Use of any antimalarial drug (% of pregnant women),Use of insecticide-treated bed nets (% of under-5 population),"Use of Intermittent Preventive Treatment of malaria, 2+ doses of SP/Fansidar (% of pregnant women)",Vitamin A supplementation coverage rate (% of children ages 6-59 months),Wanted fertility rate (births per woman),Women's share of population ages 15+ living with HIV (%),Grand Total
0,Afghanistan,NaN,NaN,NaN,6900.0,1000.0,6700.0,1000.0,NaN,NaN,...,26.703000,4.392152,NaN,NaN,NaN,NaN,NaN,NaN,28.575694,2.257291e+08
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57.407000,1.598580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.846349e+07
2,Algeria,NaN,NaN,NaN,8800.0,500.0,8600.0,500.0,NaN,NaN,...,70.727000,2.712200,NaN,NaN,NaN,NaN,NaN,NaN,45.725948,2.567538e+08
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.202000,0.115698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.116666e+05
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.115000,-3.836562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.421499e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.252000,3.225469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.952038e+07
254,World,NaN,NaN,NaN,36700000.0,2100000.0,34900000.0,1900000.0,NaN,NaN,...,53.857238,2.054434,NaN,NaN,NaN,NaN,NaN,NaN,50.836254,4.485283e+10
255,"Yemen, Rep.",NaN,NaN,NaN,9200.0,1000.0,8800.0,1000.0,NaN,NaN,...,34.606000,4.133982,NaN,NaN,NaN,NaN,NaN,NaN,41.098550,1.850650e+08
256,Zambia,NaN,NaN,NaN,1200000.0,60000.0,1100000.0,55000.0,NaN,NaN,...,40.922000,4.177551,NaN,NaN,NaN,NaN,NaN,NaN,57.244490,1.186270e+08
257,Zimbabwe,NaN,NaN,NaN,1400000.0,64000.0,1300000.0,59000.0,NaN,NaN,...,32.376000,1.928627,NaN,NaN,NaN,NaN,NaN,NaN,58.855551,1.121429e+08

## Make the column names lower case

In [4]:
def lower_case_column_names(hk_df):
    hk_df.columns=[i.lower() for i in hk_df.columns]
    return hk_df

In [5]:
lower_case_column_names(df1)

,row labels,% of females ages 15-49 having comprehensive correct knowledge about hiv (2 prevent ways and reject 3 misconceptions),% of males ages 15-49 having comprehensive correct knowledge about hiv (2 prevent ways and reject 3 misconceptions),"adolescent fertility rate (births per 1,000 women ages 15-19)",adults (ages 15+) and children (0-14 years) living with hiv,adults (ages 15+) and children (ages 0-14) newly infected with hiv,adults (ages 15+) living with hiv,adults (ages 15+) newly infected with hiv,"age at first marriage, female","age at first marriage, male",...,urban population (% of total),urban population growth (annual %),urban poverty headcount ratio at national poverty lines (% of urban population),use of any antimalarial drug (% of pregnant women),use of insecticide-treated bed nets (% of under-5 population),"use of intermittent preventive treatment of malaria, 2+ doses of sp/fansidar (% of pregnant women)",vitamin a supplementation coverage rate (% of children ages 6-59 months),wanted fertility rate (births per woman),women's share of population ages 15+ living with hiv (%),grand total
0,Afghanistan,NaN,NaN,NaN,6900.0,1000.0,6700.0,1000.0,NaN,NaN,...,26.703000,4.392152,NaN,NaN,NaN,NaN,NaN,NaN,28.575694,2.257291e+08
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57.407000,1.598580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.846349e+07
2,Algeria,NaN,NaN,NaN,8800.0,500.0,8600.0,500.0,NaN,NaN,...,70.727000,2.712200,NaN,NaN,NaN,NaN,NaN,NaN,45.725948,2.567538e+08
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.202000,0.115698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.116666e+05
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.115000,-3.836562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.421499e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.252000,3.225469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.952038e+07
254,World,NaN,NaN,NaN,36700000.0,2100000.0,34900000.0,1900000.0,NaN,NaN,...,53.857238,2.054434,NaN,NaN,NaN,NaN,NaN,NaN,50.836254,4.485283e+10
255,"Yemen, Rep.",NaN,NaN,NaN,9200.0,1000.0,8800.0,1000.0,NaN,NaN,...,34.606000,4.133982,NaN,NaN,NaN,NaN,NaN,NaN,41.098550,1.850650e+08
256,Zambia,NaN,NaN,NaN,1200000.0,60000.0,1100000.0,55000.0,NaN,NaN,...,40.922000,4.177551,NaN,NaN,NaN,NaN,NaN,NaN,57.244490,1.186270e+08
257,Zimbabwe,NaN,NaN,NaN,1400000.0,64000.0,1300000.0,59000.0,NaN,NaN,...,32.376000,1.928627,NaN,NaN,NaN,NaN,NaN,NaN,58.855551,1.121429e+08

### Describing dataset

In [6]:
df1.describe()

,% of females ages 15-49 having comprehensive correct knowledge about hiv (2 prevent ways and reject 3 misconceptions),% of males ages 15-49 having comprehensive correct knowledge about hiv (2 prevent ways and reject 3 misconceptions),"adolescent fertility rate (births per 1,000 women ages 15-19)",adults (ages 15+) and children (0-14 years) living with hiv,adults (ages 15+) and children (ages 0-14) newly infected with hiv,adults (ages 15+) living with hiv,adults (ages 15+) newly infected with hiv,"age at first marriage, female","age at first marriage, male",age dependency ratio (% of working-age population),...,urban population (% of total),urban population growth (annual %),urban poverty headcount ratio at national poverty lines (% of urban population),use of any antimalarial drug (% of pregnant women),use of insecticide-treated bed nets (% of under-5 population),"use of intermittent preventive treatment of malaria, 2+ doses of sp/fansidar (% of pregnant women)",vitamin a supplementation coverage rate (% of children ages 6-59 months),wanted fertility rate (births per woman),women's share of population ages 15+ living with hiv (%),grand total
count,4.00000,4.000000,0.0,1.080000e+02,1.080000e+02,1.080000e+02,1.080000e+02,0.0,0.0,235.000000,...,255.000000,255.000000,4.000000,0.0,4.000000,2.000000,0.0,0.0,128.000000,2.580000e+02
mean,27.55000,29.975000,NaN,6.340824e+05,3.554907e+04,6.006917e+05,3.237870e+04,NaN,NaN,58.602209,...,58.950922,1.924027,28.825000,NaN,49.200000,30.800000,NaN,NaN,43.454334,1.520014e+09
std,27.58798,26.571209,NaN,3.598206e+06,2.058210e+05,3.421136e+06,1.865082e+05,NaN,NaN,17.150947,...,23.217167,1.578634,8.391811,NaN,26.361209,20.364675,NaN,NaN,14.671469,5.022999e+09
min,6.20000,9.500000,NaN,5.000000e+02,1.000000e+02,5.000000e+02,1.000000e+02,NaN,NaN,17.751439,...,8.445000,-3.836562,19.400000,NaN,18.400000,16.400000,NaN,NaN,3.960488,2.108907e+04
25%,9.72500,15.425000,NaN,1.400000e+04,1.000000e+03,1.275000e+04,1.000000e+03,NaN,NaN,47.548600,...,39.841500,0.774438,22.925000,NaN,31.900000,23.600000,NaN,NaN,31.205632,8.601574e+06
50%,18.55000,20.800000,NaN,4.750000e+04,2.600000e+03,4.350000e+04,2.200000e+03,NaN,NaN,53.265488,...,58.964000,1.789457,30.000000,NaN,52.050000,30.800000,NaN,NaN,44.345748,6.084499e+07
75%,36.37500,35.350000,NaN,2.000000e+05,1.025000e+04,1.925000e+05,9.475000e+03,NaN,NaN,67.993228,...,78.280500,2.934841,35.900000,NaN,69.350000,38.000000,NaN,NaN,58.369387,3.174135e+08
max,66.90000,68.800000,NaN,3.670000e+07,2.100000e+06,3.490000e+07,1.900000e+06,NaN,NaN,112.972800,...,100.000000,6.432154,35.900000,NaN,74.300000,45.200000,NaN,NaN,67.145679,4.485283e+10

### Deleting columns

In [7]:
threshold_percent=0.1
print("Total records before drop",len(df1.columns))

df1_temp=df1.copy()
drop_threshold=math.floor(len(df1)*threshold_percent)
df1_temp.dropna(axis=1,thresh=drop_threshold,inplace=True)
len_of_temp=len(df1_temp.columns)
make_change=input(f"New file will contain {len_of_temp} records, commit? (y/n)")
if make_change.lower()=="y":
    df1.dropna(axis=1,thresh=drop_threshold,inplace=True)
else:
    print("Changes not implemented")

Total records before drop 347
New file will contain 212 records, commit? (y/n)y

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Columns: 212 entries, row labels to grand total
dtypes: float64(211), object(1)
memory usage: 427.4+ KB

In [9]:
df1

,row labels,adults (ages 15+) and children (0-14 years) living with hiv,adults (ages 15+) and children (ages 0-14) newly infected with hiv,adults (ages 15+) living with hiv,adults (ages 15+) newly infected with hiv,age dependency ratio (% of working-age population),"age dependency ratio, old","age dependency ratio, young","age population, age 0, female, interpolated","age population, age 0, male, interpolated",...,prevalence of undernourishment (% of population),ratio of young literate females to males (% ages 15-24),rural population,rural population (% of total population),rural population growth (annual %),urban population,urban population (% of total),urban population growth (annual %),women's share of population ages 15+ living with hiv (%),grand total
0,Afghanistan,6900.0,1000.0,6700.0,1000.0,86.954464,4.616073,82.338391,470554.0,498844.0,...,26.8,0.66416,2.384099e+07,73.297000,2.230253,8.685568e+06,26.703000,4.392152,28.575694,2.257291e+08
1,Albania,NaN,NaN,NaN,NaN,44.806973,17.950766,26.856206,21438.0,23178.0,...,NaN,1.00106,1.230583e+06,42.593000,-2.471277,1.658584e+06,57.407000,1.598580,NaN,1.846349e+07
2,Algeria,8800.0,500.0,8600.0,500.0,52.617579,9.062490,43.555089,459353.0,476141.0,...,5.0,0.99064,1.161158e+07,29.273000,-0.159154,2.805494e+07,70.727000,2.712200,45.725948,2.567538e+08
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,7.108000e+03,12.798000,0.677586,4.843000e+04,87.202000,0.115698,NaN,1.116666e+05
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.049000e+04,14.885000,0.315081,5.998300e+04,85.115000,-3.836562,NaN,1.421499e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,West Bank and Gaza,NaN,NaN,NaN,NaN,76.001869,5.209241,70.792628,72280.0,75575.0,...,NaN,0.99907,1.094392e+06,24.748000,2.015624,3.327751e+06,75.252000,3.225469,NaN,2.952038e+07
254,World,36700000.0,2100000.0,34900000.0,1900000.0,53.903376,12.597747,39.793932,NaN,NaN,...,10.8,NaN,3.378269e+09,46.142762,0.190432,3.943073e+09,53.857238,2.054434,50.836254,4.485283e+10
255,"Yemen, Rep.",9200.0,1000.0,8800.0,1000.0,75.595147,4.893864,70.701283,392662.0,409629.0,...,26.1,0.84740,1.754666e+07,65.394000,1.565199,9.285556e+06,34.606000,4.133982,41.098550,1.850650e+08
256,Zambia,1200000.0,60000.0,1100000.0,55000.0,95.402326,5.683539,89.718788,295178.0,301320.0,...,47.8,0.98069,9.577588e+06,59.078000,2.312997,6.634179e+06,40.922000,4.177551,57.244490,1.186270e+08
257,Zimbabwe,1400000.0,64000.0,1300000.0,59000.0,80.391033,5.347744,75.043289,262428.0,264810.0,...,33.4,1.03930,1.055120e+07,67.624000,2.498968,5.051547e+06,32.376000,1.928627,58.855551,1.121429e+08

In [10]:
threshold_percent=0.1
print("Total records before drop",len(df1))

df1_temp=df1.copy()
drop_threshold=math.floor(len(df1)*threshold_percent)
df1_temp.dropna(axis=0,thresh=drop_threshold,inplace=True)
len_of_temp=len(df1_temp)
make_change=input(f"New file will contain {len_of_temp} records, commit? (y/n)")
if make_change.lower()=="y":
    df1.dropna(axis=0,thresh=drop_threshold,inplace=True)
else:
    print("Changes not implemented")

Total records before drop 258
New file will contain 245 records, commit? (y/n)y

In [11]:
df1

,row labels,adults (ages 15+) and children (0-14 years) living with hiv,adults (ages 15+) and children (ages 0-14) newly infected with hiv,adults (ages 15+) living with hiv,adults (ages 15+) newly infected with hiv,age dependency ratio (% of working-age population),"age dependency ratio, old","age dependency ratio, young","age population, age 0, female, interpolated","age population, age 0, male, interpolated",...,prevalence of undernourishment (% of population),ratio of young literate females to males (% ages 15-24),rural population,rural population (% of total population),rural population growth (annual %),urban population,urban population (% of total),urban population growth (annual %),women's share of population ages 15+ living with hiv (%),grand total
0,Afghanistan,6900.0,1000.0,6700.0,1000.0,86.954464,4.616073,82.338391,470554.0,498844.0,...,26.8,0.66416,2.384099e+07,73.297000,2.230253,8.685568e+06,26.703000,4.392152,28.575694,2.257291e+08
1,Albania,NaN,NaN,NaN,NaN,44.806973,17.950766,26.856206,21438.0,23178.0,...,NaN,1.00106,1.230583e+06,42.593000,-2.471277,1.658584e+06,57.407000,1.598580,NaN,1.846349e+07
2,Algeria,8800.0,500.0,8600.0,500.0,52.617579,9.062490,43.555089,459353.0,476141.0,...,5.0,0.99064,1.161158e+07,29.273000,-0.159154,2.805494e+07,70.727000,2.712200,45.725948,2.567538e+08
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.049000e+04,14.885000,0.315081,5.998300e+04,85.115000,-3.836562,NaN,1.421499e+05
5,Angola,320000.0,26000.0,290000.0,22000.0,99.855751,4.623604,95.232147,502641.0,510719.0,...,14.2,0.85594,1.399979e+07,55.950000,1.849082,1.102218e+07,44.050000,5.003843,59.709155,1.716867e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,West Bank and Gaza,NaN,NaN,NaN,NaN,76.001869,5.209241,70.792628,72280.0,75575.0,...,NaN,0.99907,1.094392e+06,24.748000,2.015624,3.327751e+06,75.252000,3.225469,NaN,2.952038e+07
254,World,36700000.0,2100000.0,34900000.0,1900000.0,53.903376,12.597747,39.793932,NaN,NaN,...,10.8,NaN,3.378269e+09,46.142762,0.190432,3.943073e+09,53.857238,2.054434,50.836254,4.485283e+10
255,"Yemen, Rep.",9200.0,1000.0,8800.0,1000.0,75.595147,4.893864,70.701283,392662.0,409629.0,...,26.1,0.84740,1.754666e+07,65.394000,1.565199,9.285556e+06,34.606000,4.133982,41.098550,1.850650e+08
256,Zambia,1200000.0,60000.0,1100000.0,55000.0,95.402326,5.683539,89.718788,295178.0,301320.0,...,47.8,0.98069,9.577588e+06,59.078000,2.312997,6.634179e+06,40.922000,4.177551,57.244490,1.186270e+08
257,Zimbabwe,1400000.0,64000.0,1300000.0,59000.0,80.391033,5.347744,75.043289,262428.0,264810.0,...,33.4,1.03930,1.055120e+07,67.624000,2.498968,5.051547e+06,32.376000,1.928627,58.855551,1.121429e+08

In [12]:
df1.to_csv('Data/demographic country data 2.csv', index = False)

#### Copy of dataframe to rename the colmuns

In [ ]:
data_copy = df1.copy() # modifications in original data will not reflected
                        # in copied data

In [ ]:
data_copy.columns=["Col"+str(i) for i in range(len(data_copy.columns))]

In [ ]:
data_copy

In [ ]:
data_copy.info()

In [ ]:
null_data =data_copy.isnull().sum()/len(data_copy)*100

In [ ]:
null_data1 = null_data.sort_values(ascending=False)
null_data1

In [ ]:
#data_copy =data_copy.drop( axis = 1, inplace = True)

### Aplying PCA

In [ ]:
pca = PCA()
X = pca.fit_transform(df1)