# Exploratory Data Analysis (EDA)

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import glob
import qgrid

## Loading the Dataset

In [2]:
def load_csv_dataframes(path):
    '''Loads all csv files in a folder and stores them in a list of dataframes.
    Returns list of dataframes.
    [attributes]
    path: path of folder with csvs inside
    '''
    all_files = glob.glob(path + "/*.csv")
    dataframes_list=[]
    file_count=len(all_files)
    for i in range(file_count):
        temp_df = pd.read_csv(all_files[i])
        dataframes_list.append(temp_df)
        
    return dataframes_list

In [3]:
####1. Load relevant csv files. 
### INPUT -- folder_path for file

# Update folder_path to grab all csv files in folder
folder_path = r"C:\Users\Barbara\OneDrive\Documents\GitHub\IH_Berliners\Data\1. Files to merge\combined_data_merged.csv"

df= pd.read_csv(folder_path)#
#df.drop('Unnamed: 0', inplace=True, axis=1)

In [4]:
df

,country,adults (ages 15+) and children (0-14 years) living with hiv,adults (ages 15+) and children (ages 0-14) newly infected with hiv,adults (ages 15+) living with hiv,adults (ages 15+) newly infected with hiv,age dependency ratio (% of working-age population),"age dependency ratio, old","age dependency ratio, young","age population, age 0, female, interpolated","age population, age 0, male, interpolated",...,protein_spices,protein_starchy roots,protein_stimulants,protein_sugar & sweeteners,protein_treenuts,protein_vegetal products,protein_vegetable oils,protein_vegetables,protein_miscellaneous,mortality_rate_covid
0,afghanistan,6900.0,1000.0,6700.0,1000.0,86.954464,4.616073,82.338391,470554.0,498844.0,...,0.1664,0.1941,0.5546,0.0000,0.1387,40.2477,0.0000,1.1370,0.0462,4.352069
1,albania,NaN,NaN,NaN,NaN,44.806973,17.950766,26.856206,21438.0,23178.0,...,0.0000,0.8867,0.2635,0.0042,0.2677,22.2552,0.0084,3.2456,0.0544,1.717095
2,algeria,8800.0,500.0,8600.0,500.0,52.617579,9.062490,43.555089,459353.0,476141.0,...,0.1776,1.4638,0.4628,0.0000,0.2745,36.1694,0.0269,3.1267,0.1399,2.677922
3,angola,320000.0,26000.0,290000.0,22000.0,99.855751,4.623604,95.232147,502641.0,510719.0,...,0.0000,5.1941,0.1017,0.0092,0.0092,34.7782,0.0092,0.8133,0.0924,2.367660
4,antigua and barbuda,NaN,NaN,NaN,NaN,45.650381,10.434645,35.215736,734.0,744.0,...,0.3438,0.4666,0.4113,0.0000,0.0737,16.8161,0.0430,1.6024,0.2947,2.430556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,venezuela,110000.0,5600.0,110000.0,5300.0,52.374932,9.549329,42.825603,289792.0,303680.0,...,0.0000,1.1195,0.3287,0.0178,0.0000,27.4545,0.0533,1.0129,0.0267,NaN
159,vietnam,260000.0,14000.0,250000.0,14000.0,42.511440,9.605993,32.905446,733682.0,816544.0,...,0.5221,0.2333,0.5444,0.0056,0.3277,29.5617,0.0000,3.7216,0.0389,NaN
160,yemen,9200.0,1000.0,8800.0,1000.0,75.595147,4.893864,70.701283,392662.0,409629.0,...,0.0657,0.2066,0.3193,0.0000,0.0188,39.9831,0.0000,0.5448,0.0564,NaN
161,zambia,1200000.0,60000.0,1100000.0,55000.0,95.402326,5.683539,89.718788,295178.0,301320.0,...,0.0846,1.2863,0.0762,0.0000,0.0000,40.1117,0.0000,0.8039,0.0592,NaN
162,zimbabwe,1400000.0,64000.0,1300000.0,59000.0,80.391033,5.347744,75.043289,262428.0,264810.0,...,0.0488,0.5467,0.2636,0.0000,0.1367,38.6508,0.0293,0.5955,0.0586,NaN

## Structured Based <span class="mark">Data Exploration</span>

<b> Displaying the first 5 rows

In [5]:
df.head()

,country,adults (ages 15+) and children (0-14 years) living with hiv,adults (ages 15+) and children (ages 0-14) newly infected with hiv,adults (ages 15+) living with hiv,adults (ages 15+) newly infected with hiv,age dependency ratio (% of working-age population),"age dependency ratio, old","age dependency ratio, young","age population, age 0, female, interpolated","age population, age 0, male, interpolated",...,protein_spices,protein_starchy roots,protein_stimulants,protein_sugar & sweeteners,protein_treenuts,protein_vegetal products,protein_vegetable oils,protein_vegetables,protein_miscellaneous,mortality_rate_covid
0,afghanistan,6900.0,1000.0,6700.0,1000.0,86.954464,4.616073,82.338391,470554.0,498844.0,...,0.1664,0.1941,0.5546,0.0000,0.1387,40.2477,0.0000,1.1370,0.0462,4.352069
1,albania,NaN,NaN,NaN,NaN,44.806973,17.950766,26.856206,21438.0,23178.0,...,0.0000,0.8867,0.2635,0.0042,0.2677,22.2552,0.0084,3.2456,0.0544,1.717095
2,algeria,8800.0,500.0,8600.0,500.0,52.617579,9.062490,43.555089,459353.0,476141.0,...,0.1776,1.4638,0.4628,0.0000,0.2745,36.1694,0.0269,3.1267,0.1399,2.677922
3,angola,320000.0,26000.0,290000.0,22000.0,99.855751,4.623604,95.232147,502641.0,510719.0,...,0.0000,5.1941,0.1017,0.0092,0.0092,34.7782,0.0092,0.8133,0.0924,2.367660
4,antigua and barbuda,NaN,NaN,NaN,NaN,45.650381,10.434645,35.215736,734.0,744.0,...,0.3438,0.4666,0.4113,0.0000,0.0737,16.8161,0.0430,1.6024,0.2947,2.430556

<b> Displaying the last 5 rows

In [6]:
df.tail()

,country,adults (ages 15+) and children (0-14 years) living with hiv,adults (ages 15+) and children (ages 0-14) newly infected with hiv,adults (ages 15+) living with hiv,adults (ages 15+) newly infected with hiv,age dependency ratio (% of working-age population),"age dependency ratio, old","age dependency ratio, young","age population, age 0, female, interpolated","age population, age 0, male, interpolated",...,protein_spices,protein_starchy roots,protein_stimulants,protein_sugar & sweeteners,protein_treenuts,protein_vegetal products,protein_vegetable oils,protein_vegetables,protein_miscellaneous,mortality_rate_covid
158,venezuela,110000.0,5600.0,110000.0,5300.0,52.374932,9.549329,42.825603,289792.0,303680.0,...,0.0000,1.1195,0.3287,0.0178,0.0000,27.4545,0.0533,1.0129,0.0267,NaN
159,vietnam,260000.0,14000.0,250000.0,14000.0,42.511440,9.605993,32.905446,733682.0,816544.0,...,0.5221,0.2333,0.5444,0.0056,0.3277,29.5617,0.0000,3.7216,0.0389,NaN
160,yemen,9200.0,1000.0,8800.0,1000.0,75.595147,4.893864,70.701283,392662.0,409629.0,...,0.0657,0.2066,0.3193,0.0000,0.0188,39.9831,0.0000,0.5448,0.0564,NaN
161,zambia,1200000.0,60000.0,1100000.0,55000.0,95.402326,5.683539,89.718788,295178.0,301320.0,...,0.0846,1.2863,0.0762,0.0000,0.0000,40.1117,0.0000,0.8039,0.0592,NaN
162,zimbabwe,1400000.0,64000.0,1300000.0,59000.0,80.391033,5.347744,75.043289,262428.0,264810.0,...,0.0488,0.5467,0.2636,0.0000,0.1367,38.6508,0.0293,0.5955,0.0586,NaN

<b> Displaying the Number of Variables and Observations

In [7]:
#In this Dataframe, there are 162 rows X 256 columns
df.shape

(163, 277)

<b> Display the Variable Names and Data Types

In [8]:
qgrid.show_grid(df.dtypes, grid_options={'forceFitColumns': False})

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': False, 'defa…

<b> Count the number of Non-Missing Values for each variable

In [9]:
qgrid.show_grid(df.count(), grid_options={'forceFitColumns': False})

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': False, 'defa…

<b> Descriptive Statistics

In [10]:
#Statistical information of all numerical features in the dataframe
qgrid.show_grid(df.describe(), grid_options={'forceFitColumns': False})

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': False, 'defa…

<b> Displaying the Complete Summary of the Dataset

In [11]:
qgrid.show_grid(df.info(verbose = True), grid_options={'forceFitColumns': False})

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 277 columns):
 #    Column                                                                           Dtype
---   ------                                                                           -----
 0    country                                                                          object
 1    adults (ages 15+) and children (0-14 years) living with hiv                      float64
 2    adults (ages 15+) and children (ages 0-14) newly infected with hiv               float64
 3    adults (ages 15+) living with hiv                                                float64
 4    adults (ages 15+) newly infected with hiv                                        float64
 5    age dependency ratio (% of working-age population)                               float64
 6    age dependency ratio, old                                                        float64
 7    age dependency ratio, young                                                      float64
 8    age population, age 0, female, interpolated                                      float64
 9    age population, age 0, male, interpolated                                        float64
 10   age population, age 01, female, interpolated                                     float64
 11   age population, age 01, male, interpolated                                       float64
 12   age population, age 02, female, interpolated                                     float64
 13   age population, age 02, male, interpolated                                       float64
 14   age population, age 03, female, interpolated                                     float64
 15   age population, age 03, male, interpolated                                       float64
 16   age population, age 04, female, interpolated                                     float64
 17   age population, age 04, male, interpolated                                       float64
 18   age population, age 05, female, interpolated                                     float64
 19   age population, age 05, male, interpolated                                       float64
 20   age population, age 06, female, interpolated                                     float64
 21   age population, age 06, male, interpolated                                       float64
 22   age population, age 07, female, interpolated                                     float64
 23   age population, age 07, male, interpolated                                       float64
 24   age population, age 08, female, interpolated                                     float64
 25   age population, age 08, male, interpolated                                       float64
 26   age population, age 09, female, interpolated                                     float64
 27   age population, age 09, male, interpolated                                       float64
 28   age population, age 10, female, interpolated                                     float64
 29   age population, age 10, male, interpolated                                       float64
 30   age population, age 11, female, interpolated                                     float64
 31   age population, age 11, male, interpolated                                       float64
 32   age population, age 12, female, interpolated                                     float64
 33   age population, age 12, male, interpolated                                       float64
 34   age population, age 13, female, interpolated                                     float64
 35   age population, age 13, male, interpolated                                       float64
 36   age population, age 14, female, interpolated                                     float64
 37   age population, age 14, male, interpolated                                       float64
 38   age population, age 15, female, interpolated                                     float64
 39   age population, age 15, male, interpolated                                       float64
 40   age population, age 16, female, interpolated                                     float64
 41   age population, age 16, male, interpolated                                       float64
 42   age population, age 17, female, interpolated                                     float64
 43   age population, age 17, male, interpolated                                       float64
 44   age population, age 18, female, interpolated                                     float64
 45   age population, age 18, male, interpolated                                       float64
 46   age population, age 19, female, interpolated                                     float64
 47   age population, age 19, male, interpolated                                       float64
 48   age population, age 20, female, interpolated                                     float64
 49   age population, age 20, male, interpolated                                       float64
 50   age population, age 21, female, interpolated                                     float64
 51   age population, age 21, male, interpolated                                       float64
 52   age population, age 22, female, interpolated                                     float64
 53   age population, age 22, male, interpolated                                       float64
 54   age population, age 23, female, interpolated                                     float64
 55   age population, age 23, male, interpolated                                       float64
 56   age population, age 24, female, interpolated                                     float64
 57   age population, age 24, male, interpolated                                       float64
 58   age population, age 25, female, interpolated                                     float64
 59   age population, age 25, male, interpolated                                       float64
 60   aids estimated deaths (unaids estimates)                                         float64
 61   antiretroviral therapy coverage (% of people living with hiv)                    float64
 62   antiretroviral therapy coverage for pmtct (% of pregnant women living with hiv)  float64
 63   children (0-14) living with hiv                                                  float64
 64   children (ages 0-14) newly infected with hiv                                     float64
 65   children orphaned by hiv/aids                                                    float64
 66   diabetes prevalence (% of population ages 20 to 79)                              float64
 67   female population 00-04                                                          float64
 68   female population 05-09                                                          float64
 69   female population 10-14                                                          float64
 70   female population 15-19                                                          float64
 71   female population 20-24                                                          float64
 72   female population 25-29                                                          float64
 73   female population 30-34                                                          float64
 74   female population 35-39                                                          float64
 75   female population 40-44                                                          float64
 76   female population 45-49                                                          float64
 77   female population 50-54                                                          float64
 78   female population 55-59                                                          float64
 79   female population 60-64                                                          float64
 80   female population 65-69                                                          float64
 81   female population 70-74                                                          float64
 82   female population 75-79                                                          float64
 83   female population 80+                                                            float64
 84   gni per capita, atlas method (current us$)                                       float64
 85   immunization, bcg (% of one-year-old children)                                   float64
 86   immunization, dpt (% of children ages 12-23 months)                              float64
 87   immunization, hepb3 (% of one-year-old children)                                 float64
 88   immunization, hib3 (% of children ages 12-23 months)                             float64
 89   immunization, measles (% of children ages 12-23 months)                          float64
 90   immunization, pol3 (% of one-year-old children)                                  float64
 91   improved sanitation facilities (% of population with access)                     float64
 92   improved sanitation facilities, rural (% of rural population with access)        float64
 93   improved sanitation facilities, urban (% of urban population with access)        float64
 94   improved water source (% of population with access)                              float64
 95   improved water source, rural (% of rural population with access)                 float64
 96   improved water source, urban (% of urban population with access)                 float64
 97   incidence of hiv (% of uninfected population ages 15-49)                         float64
 98   lifetime risk of maternal death (%)                                              float64
 99   lifetime risk of maternal death (1 in: rate varies by country)                   float64
 100  literacy rate, adult female (% of females ages 15 and above)                     float64
 101  literacy rate, adult male (% of males ages 15 and above)                         float64
 102  literacy rate, adult total (% of people ages 15 and above)                       float64
 103  literacy rate, youth male (% of males ages 15-24)                                float64
 104  literacy rate, youth total (% of people ages 15-24)                              float64
 105  male population 00-04                                                            float64
 106  male population 05-09                                                            float64
 107  male population 10-14                                                            float64
 108  male population 15-19                                                            float64
 109  male population 20-24                                                            float64
 110  male population 25-29                                                            float64
 111  male population 30-34                                                            float64
 112  male population 35-39                                                            float64
 113  male population 40-44                                                            float64
 114  male population 45-49                                                            float64
 115  male population 50-54                                                            float64
 116  male population 55-59                                                            float64
 117  male population 60-64                                                            float64
 118  male population 65-69                                                            float64
 119  male population 70-74                                                            float64
 120  male population 75-79                                                            float64
 121  male population 80+                                                              float64
 122  maternal leave benefits (% of wages paid in covered period)                      float64
 123  maternal mortality ratio (modeled estimate, per 100,000 live births)             float64
 124  mortality rate, infant (per 1,000 live births)                                   float64
 125  mortality rate, infant, female (per 1,000 live births)                           float64
 126  mortality rate, infant, male (per 1,000 live births)                             float64
 127  mortality rate, neonatal (per 1,000 live births)                                 float64
 128  mortality rate, under-5 (per 1,000)                                              float64
 129  mortality rate, under-5, female (per 1,000)                                      float64
 130  mortality rate, under-5, male (per 1,000)                                        float64
 131  newborns protected against tetanus (%)                                           float64
 132  number of infant deaths                                                          float64
 133  number of maternal deaths                                                        float64
 134  number of neonatal deaths                                                        float64
 135  number of people who are undernourished                                          float64
 136  number of under-five deaths                                                      float64
 137  number of weeks of maternity leave                                               float64
 138  people practicing open defecation (% of population)                              float64
 139  people practicing open defecation, rural (% of rural population)                 float64
 140  people practicing open defecation, urban (% of urban population)                 float64
 141  population ages 00-04, female (% of female population)                           float64
 142  population ages 00-04, male (% of male population)                               float64
 143  population ages 00-14 (% of total)                                               float64
 144  population ages 00-14, female (% of total)                                       float64
 145  population ages 00-14, male (% of total)                                         float64
 146  population ages 00-14, total                                                     float64
 147  population ages 0-14, female                                                     float64
 148  population ages 0-14, male                                                       float64
 149  population ages 05-09, female (% of female population)                           float64
 150  population ages 05-09, male (% of male population)                               float64
 151  population ages 10-14, female (% of female population)                           float64
 152  population ages 15-19, female (% of female population)                           float64
 153  population ages 15-19, male (% of male population)                               float64
 154  population ages 15-64 (% of total)                                               float64
 155  population ages 15-64, female                                                    float64
 156  population ages 15-64, female (% of total)                                       float64
 157  population ages 15-64, male                                                      float64
 158  population ages 15-64, male (% of total)                                         float64
 159  population ages 15-64, total                                                     float64
 160  population ages 20-24, female (% of female population)                           float64
 161  population ages 20-24, male (% of male population)                               float64
 162  population ages 25-29, female (% of female population)                           float64
 163  population ages 25-29, male (% of male population)                               float64
 164  population ages 30-34, female (% of female population)                           float64
 165  population ages 30-34, male (% of male population)                               float64
 166  population ages 35-39, female (% of female population)                           float64
 167  population ages 35-39, male (% of male population)                               float64
 168  population ages 40-44, female (% of female population)                           float64
 169  population ages 40-44, male (% of male population)                               float64
 170  population ages 45-49, female (% of female population)                           float64
 171  population ages 45-49, male (% of male population)                               float64
 172  population ages 50-54, female (% of female population)                           float64
 173  population ages 50-54, male (% of male population)                               float64
 174  population ages 55-59, female (% of female population)                           float64
 175  population ages 55-59, male (% of male population)                               float64
 176  population ages 60-64, female (% of female population)                           float64
 177  population ages 60-64, male (% of male population)                               float64
 178  population ages 65 and above (% of total)                                        float64
 179  population ages 65 and above, female                                             float64
 180  population ages 65 and above, female (% of total)                                float64
 181  population ages 65 and above, male                                               float64
 182  population ages 65 and above, male (% of total)                                  float64
 183  population ages 65 and above, total                                              float64
 184  population ages 65-69, female (% of female population)                           float64
 185  population ages 65-69, male (% of male population)                               float64
 186  population ages 70-74, female (% of female population)                           float64
 187  population ages 70-74, male (% of male population)                               float64
 188  population ages 75-79, female (% of female population)                           float64
 189  population ages 75-79, male (% of male population)                               float64
 190  population ages 80 and older, female (% of female population)                    float64
 191  population ages 80 and older, male (% of male population)                        float64
 192  population ages10-14, male (% of male population)                                float64
 193  population growth (annual %)                                                     float64
 194  population, female                                                               float64
 195  population, female (% of total)                                                  float64
 196  population, male                                                                 float64
 197  population, male (% of total)                                                    float64
 198  population, total                                                                float64
 199  prevalence of hiv, female (% ages 15-24)                                         float64
 200  prevalence of hiv, male (% ages 15-24)                                           float64
 201  prevalence of hiv, total (% of population ages 15-49)                            float64
 202  prevalence of undernourishment (% of population)                                 float64
 203  ratio of young literate females to males (% ages 15-24)                          float64
 204  rural population                                                                 float64
 205  rural population (% of total population)                                         float64
 206  rural population growth (annual %)                                               float64

TypeError: data_frame must be DataFrame or Series, not <class 'NoneType'>

<b> Null vaues

In [ ]:
qgrid.show_grid(df.isnull().sum(), grid_options={'forceFitColumns': False})

# Data Visualizations

## Target Variable

In [ ]:
plt.scatter(df.index,df['mortality_rate_covid'])
plt.title("Univariate scatter plot")
plt.xlabel("Observation number")
plt.ylabel("mortality_rate_covid")
plt.show()

## Correlation matrix

### Deleting correlated variables (90% treshold)

In [ ]:
def correlation(dataset, threshold):
    col_corr = set() # Set of all the names of deleted columns
    corr_matrix = dataset.corr().abs()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if (corr_matrix.iloc[i, j] >= threshold) and (corr_matrix.columns[j] not in col_corr):
                colname = corr_matrix.columns[i] # getting the name of column
                col_corr.add(colname)
                if colname in dataset.columns:
                    del dataset[colname] # deleting the column from the dataset

    return dataset

In [ ]:
corr90 = correlation(df, 0.9)

<b> Dataframe with dropped columns

In [ ]:
corr90

In [ ]:
#corr90.columns

### Correlation matrix

In [ ]:
corr_matrix=df.corr()

qgrid.show_grid(corr_matrix.abs(), grid_options={'forceFitColumns': False})

In [ ]:
plt.figure(figsize=(9, 8))
sns.distplot(df['mortality_rate_covid'], color='g', bins=100, hist_kws={'alpha': 0.4});

In [ ]:
df_num = df.select_dtypes(include = ['float64', 'int64'])
df_num.head()

In [ ]:
df_num.hist(figsize=(40, 35), bins=50, xlabelsize=15, ylabelsize=10);

In [ ]:
numeric=df._get_numeric_data()
col_names=numeric.columns
for i in col_names:
    plt.figure(figsize=(9,5))
    sns.boxplot(x=i,data=df)

<b> Removing outliers

In [ ]:
def remove_outlier_IQR(df):
    Q1=df.quantile(0.25)
    Q3=df.quantile(0.75)
    IQR=Q3-Q1
    df_final=df[~((df<(Q1-1.5*IQR)) | (df>(Q3+1.5*IQR)))]
    return df_final

In [ ]:
df_without_outliers = remove_outlier_IQR(numeric)
df_without_outliers

<b> Replaicng NANs with mean and multuple columns

In [ ]:
column_means = numeric.mean()
df = df_without_outliers.fillna(column_means)

### Boxplots with data cleaned

In [ ]:
df=df._get_numeric_data()
col_names=numeric.columns
for i in col_names:
    plt.figure(figsize=(9,5))
    sns.boxplot(x=i,data=df)

### Scatter plots with Cleaned Dataframe

In [ ]:
df=df._get_numeric_data()
col_names=numeric.columns
for i in col_names:
    plt.figure(figsize=(9,5))
    sns.scatterplot(data=df, x=i,y=df['covid_deaths'] )

age population, age 0, female, interpolated
inmunization, dpt(%children ages 12-23 months) ???
inmunization, hib3(%children ages 12-23 months) 
inmunization, measles(%children ages 12-23 months)

In [ ]:
####1. Load relevant csv files. 
### INPUT -- folder_path for file
# Update folder_path to grab all csv files in folder
folder_path = r"Data\\6.gni and comparative death rates\nutrition_demographic_covid_continent_3.csv"
df1= pd.read_csv(folder_path)

In [ ]:
gni_higher = df1[df1['gni_real']== 'high_gni']
df2=gni_higher._get_numeric_data()
col_names=numeric.columns
for i in col_names:
    plt.figure(figsize=(9,5))
    sns.scatterplot(data=df2, x=i,y=df2['covid_deaths'] )

In [ ]:
gni_higher = df1[df1['gni_real']== 'low_gni']
df2=gni_higher._get_numeric_data()
col_names=numeric.columns
for i in col_names:
    plt.figure(figsize=(9,5))
    sns.scatterplot(data=df2, x=i,y=df2['covid_deaths'] )

In [ ]:
####1. Load relevant csv files. 
### INPUT -- folder_path for file
# Update folder_path to grab all csv files in folder
folder_path = r"C:\Users\Barbara\OneDrive\Documents\GitHub\IH_Berliners\Data\4. Updated Covid numbers\nutrition_demographic_covid.csv"
df3= pd.read_csv(folder_path)

In [ ]:
df4=df3._get_numeric_data()
col_names=df4.columns
for i in col_names:
    plt.figure(figsize=(9,5))
    sns.scatterplot(data=df4, x=i,y=df4['covid_fatality_rate'] )

In [ ]:

df4.columns